resolve correct paths in glutin 0.23.0
This fixes paths to the structs needed in the tutorial. Note that tutorial still doesn't work with these fixes due to 
```
error[E0599]: no method named `poll_events` found for type `glium::glutin::event_loop::EventLoop<()>`
```